// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/cart/addItems.ts";
import * as $$$$$$$$$1 from "./actions/cart/updateItems.ts";
import * as $$$$0 from "./handlers/sitemap.ts";
import * as $$$0 from "./loaders/cart.ts";
import * as $$$1 from "./loaders/productDetailsPage.ts";
import * as $$$2 from "./loaders/productList.ts";
import * as $$$3 from "./loaders/productListingPage.ts";
import * as $$$4 from "./loaders/proxy.ts";

const manifest = {
  "loaders": {
    "n49shop/loaders/cart.ts": $$$0,
    "n49shop/loaders/productDetailsPage.ts": $$$1,
    "n49shop/loaders/productList.ts": $$$2,
    "n49shop/loaders/productListingPage.ts": $$$3,
    "n49shop/loaders/proxy.ts": $$$4,
  },
  "handlers": {
    "n49shop/handlers/sitemap.ts": $$$$0,
  },
  "actions": {
    "n49shop/actions/cart/addItems.ts": $$$$$$$$$0,
    "n49shop/actions/cart/updateItems.ts": $$$$$$$$$1,
  },
  "name": "n49shop",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
